### ISSUE TITLE
Update landing page for next version

### ISSUE THREAD

**Issue by dpsnowden** [ioos/ioos-metadata#1]
Catching a couple topics here.  The main landing [page](https://github.com/ioos/ioos-netcdf/blob/gh-pages/_docs/index.md) should be updated whenever we publish the draft 1.2 standard.  

1. Remove the references to SOS in the introductory paragraph.  We can put that at the bottom of the page as an additional piece of information.  But the main purpose of this standard is to define the netCDF standard as a stand alone data content standard.  It doesn't exist simply to do the crosswalk.

2. Move the supporting standards underneath the versions.  ACCD 1.3/CF 1.6/NCEI 2.0 all correspond to IOOS 1.1  ==> ACDD1.3/CF1.7/NCEI 2.0 will probably correspond to the IOOS 1.2.  etc...  This gives us a chance to evolve the IOOS spec as the others move.

**Comment by mwengren** [comment]
@dpsnowden The home page has been updated and mostly rewritten.  Note new URL reflecting the name change of the repo: https://ioos.github.io/ioos-metadata/ .  This should include the changes you requested, closing this issue.
